<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Option;
use App\Models\Question;

class OptionSeeder extends Seeder
{
    public function run(): void
    {
        $options = [
            // SQA Questions
            // Basic SQA Questions
            [
                ['A process to ensure software quality', true],
                ['A type of software', false],
                ['A programming language', false],
                ['A testing tool', false],
                ['None of the above', false],
            ],
            [
                ['Design', false],
                ['Implementation', false],
                ['Testing', false],
                ['Maintenance', false],
                ['None of the above', true],
            ],
            [
                ['To find bugs', false],
                ['To ensure code quality', false],
                ['To validate software functionality', true],
                ['To improve performance', false],
                ['None of the above', false],
            ],
            [
                ['Verification ensures the product is built right', true],
                ['Validation ensures the product is built correctly', false],
                ['Both are the same', false],
                ['Verification is done by users', false],
                ['None of the above', false],
            ],
            [
                ['An error in the software', true],
                ['A feature of the software', false],
                ['A type of testing', false],
                ['A programming bug', false],
                ['None of the above', false],
            ],
            [
                ['A type of software', false],
                ['An error in the software', true],
                ['A testing method', false],
                ['A programming language', false],
                ['None of the above', false],
            ],
            [
                ['Selenium', true],
                ['JUnit', false],
                ['TestNG', false],
                ['Cucumber', false],
                ['None of the above', false],
            ],
            [
                ['A document that describes test cases', true],
                ['A type of software', false],
                ['A testing tool', false],
                ['A programming language', false],
                ['None of the above', false],
            ],
            [
                ['To outline testing strategy', true],
                ['To write code', false],
                ['To manage teams', false],
                ['To deploy software', false],
                ['None of the above', false],
            ],
            [
                ['Testing after changes', true],
                ['Testing before release', false],
                ['Testing during development', false],
                ['Testing for performance', false],
                ['None of the above', false],
            ],
            [
                ['To check system performance', true],
                ['To check system security', false],
                ['To check system functionality', false],
                ['To check system usability', false],
                ['None of the above', false],
            ],
            [
                ['White-box testing', false],
                ['Black-box testing', true],
                ['Gray-box testing', false],
                ['Unit testing', false],
                ['None of the above', false],
            ],
            [
                ['A script that automates testing', true],
                ['A document that describes tests', false],
                ['A type of testing', false],
                ['A programming language', false],
                ['None of the above', false],
            ],
            [
                ['To explore the software', true],
                ['To write code', false],
                ['To manage teams', false],
                ['To deploy software', false],
                ['None of the above', false],
            ],
            [
                ['To check system performance', true],
                ['To check system security', false],
                ['To check system functionality', false],
                ['To check system usability', false],
                ['None of the above', false],
            ],

            // Intermediate SQA Questions
            [
                ['To find bugs early', true],
                ['To improve performance', false],
                ['To write code', false],
                ['To manage teams', false],
                ['None of the above', false],
            ],
            [
                ['Black-box testing focuses on inputs and outputs', true],
                ['White-box testing focuses on code structure', true],
                ['Both are the same', false],
                ['Black-box testing is done by developers', false],
                ['None of the above', false],
            ],
            [
                ['Integration testing', true],
                ['Unit testing', false],
                ['System testing', false],
                ['Acceptance testing', false],
                ['None of the above', false],
            ],
            [
                ['To manage testing teams', false],
                ['To oversee testing processes', true],
                ['To write code', false],
                ['To deploy software', false],
 ['None of the above', false],
            ],
            [
                ['Stress testing checks system limits', true],
                ['Performance testing checks functionality', false],
                ['Both are the same', false],
                ['Stress testing is done by users', false],
                ['None of the above', false],
            ],
            [
                ['A scenario for testing', true],
                ['A type of testing', false],
                ['A programming language', false],
                ['A testing tool', false],
                ['None of the above', false],
            ],
            [
                ['A collection of test cases', true],
                ['A type of testing', false],
                ['A programming language', false],
                ['A testing tool', false],
                ['None of the above', false],
            ],
            [
                ['End-users conduct it', true],
                ['Developers conduct it', false],
                ['Testers conduct it', false],
                ['Automated tools conduct it', false],
                ['None of the above', false],
            ],
            [
                ['To track bugs', true],
                ['To write code', false],
                ['To manage teams', false],
                ['To deploy software', false],
                ['None of the above', false],
            ],
            [
                ['To validate software against requirements', true],
                ['To check performance', false],
                ['To write code', false],
                ['To manage teams', false],
                ['None of the above', false],
            ],
            [
                ['A setup for testing', true],
                ['A type of testing', false],
                ['A programming language', false],
                ['A testing tool', false],
                ['None of the above', false],
            ],
            [
                ['Agile methodology', true],
                ['Waterfall methodology', false],
                ['V-Model', false],
                ['Spiral model', false],
                ['None of the above', false],
            ],
            [
                ['To outline testing strategy', true],
                ['To write code', false],
                ['To manage teams', false],
                ['To deploy software', false],
                ['None of the above', false],
            ],
            [
                ['Automating tests', true],
                ['Writing code', false],
                ['Managing teams', false],
                ['Deploying software', false],
                ['None of the above', false],
            ],
            [
                ['To ensure quality', true],
                ['To write code', false],
                ['To manage teams', false],
                ['To deploy software', false],
                ['None of the above', false],
            ],

            // Advanced SQA Questions
            [
                ['Defect density measures defects per size', true],
                ['Defect priority measures severity', false],
                ['Both are the same', false],
                ['Defect density is irrelevant', false],
                ['None of the above', false],
            ],
            [
                ['To prioritize testing efforts', true],
                ['To write code', false],
                ['To manage teams', false],
                ['To deploy software', false],
                ['None of the above', false],
            ],
            [
                ['To design test strategies', true],
                ['To write code', false],
                ['To manage teams', false],
                ['To deploy software', false],
                ['None of the above', false],
            ],
            [
                ['Testing in pairs', true],
                ['Testing alone', false],
                ['Automated testing', false],
                ['Unit testing', false],
                ['None of the above', false],
            ],
            [
                ['To measure code quality', true],
                ['To write code', false],
                ['To manage teams', false],
                ['To deploy software', false],
                ['None of the above', false],
            ],
            [
                ['To find edge cases', true],
                ['To write code', false],
                ['To manage teams', false],
                ['To deploy software', false],
                ['None of the above', false],
            ],
            [
                ['To identify root causes of defects', true],
                ['To write code', false],
                ['To manage teams', false],
                ['To deploy software', false],
                ['None of the above', false],
            ],
            [
                ['A point where performance slows', true],
                ['A type of testing', false],
                ['A programming language', false],
                ['A testing tool', false],
                ['None of the above', false],
            ],
            [
                ['To measure testing effectiveness', true],
                ['To write code', false],
                ['To manage teams', false],
                ['To deploy software', false],
                ['None of the above', false],
            ],
            [
                ['Validation checks if the product meets requirements', true],
                ['Qualification checks if the product is usable', false],
                ['Both are the same', false],
                ['Validation is irrelevant', false],
                ['None of the above', false],
            ],
            [
                ['To reduce risks in testing', true],
                ['To write code', false],
                ['To manage teams', false],
                ['To deploy software', false],
                ['None of the above', false],
            ],
            [
                ['Continuous testing ensures quality in Agile', true],
                ['Continuous testing is irrelevant', false],
                ['Continuous testing is only for manual testing', false],
                ['Continuous testing is not necessary', false],
                ['None of the above', false],
            ],
            [
                ['Writing tests before code', true],
                ['Writing code before tests', false],
                ['Both are the same', false],
                ['Test-driven development is irrelevant', false],
                ['None of the above', false],
            ],
            [
                ['A framework for assessing software quality', true],
                ['A programming language', false],
                ['A testing tool', false],
                ['A type of testing', false],
                ['None of the above', false],
            ],
            [
                ['A model for assessing testing maturity', true],
                ['A programming language', false],
                ['A testing tool', false],
                ['A type of testing', false],
                ['None of the above', false],
            ],

            // Networking Questions
            // Basic Networking Questions
            [
                ['A collection of servers', false],
                ['A group of connected devices for communication', true],
                ['A single device', false],
                ['A type of programming language', false],
                ['None of the above', false],
            ],
            [
                ['Internet Provider', false],
                ['Information Protocol', false],
                ['Internet Protocol', true],
                ['Internal Provider', false],
                ['Integrated Programming', false],
            ],
            [
                ['Switch', false],
                ['Hub', false],
                ['Router', true],
                ['Repeater', false],
                ['Firewall', false],
            ],
            [
                ['Boost network speed', false],
                ['Protect against unauthorized access', true],
                ['Store data', false],
                ['Manage user permissions', false],
                ['Improve signal strength', false],
            ],
            [
                ['Frame', false],
                ['Packet', true],
                ['Byte', false],
                ['Segment', false],
                ['Cluster', false],
            ],
            [
                ['HTTP', false],
                ['FTP', false],
                ['SMTP', true],
                ['DNS', false],
                ['SNMP', false],
            ],
            [
                ['Local Access Network', false],
                ['Local Area Network', true],
                ['Long Area Network', false],
                ['Large Access Network', false],
                ['Line Access Network', false],
            ],
            [
                ['Transport Layer', false],
                ['Application Layer', false],
                ['Session Layer', false],
                ['Presentation Layer', true],
                ['Physical Layer', false],
            ],
            [
                ['Provides IP addresses', false],
                ['Translates domain names to IP addresses', true],
                ['Routes packets', false],
                ['Blocks unauthorized access', false],
                ['Increases bandwidth', false],
            ],
            [
                ['255.0.0.0', false],
                ['255.255.0.0', false],
                ['255.255.255.0', true],
                ['255.255.255.255', false],
                ['255.255.252.0', false],
            ],
            [
                ['Network security', false],
                ['Speed of the internet', false],
                ['Connectivity between devices', true],
                ['DNS server response', false],
                ['Firewall configuration', false],
            ],
            [
                ['FTP', false],
                ['HTTP', false],
                ['HTTPS', true],
                ['SMTP', false],
                ['POP3', false],
            ],
            [
                ['Public IP Address', false],
                ['MAC Address', false],
                ['Private IP Address', true],
                ['Loopback Address', false],
                ['Broadcast Address', false],
            ],
            [
                ['Router', false],
                ['Switch', true],
                ['Firewall', false],
                ['Modem', false],
                ['Application Server', false],
            ],
            [
                ['Ring topology', false],
                ['Mesh topology', false],
                ['Bus topology', false],
                ['Star topology', true],
                ['Tree topology', false],
            ],

            // Intermediate Networking Questions
            [
                ['255.0.0.0', false],
                ['255.255.0.0', true],
                ['255.255.255.0', false],
                ['255.255.255.255', false],
                ['None of the above', false],
            ],
            [
                ['Physical', false],
                ['Network', false],
                ['Transport', true],
                ['Application', false],
                ['Data Link', false],
            ],
            [
                ['Resolve domain names to IP addresses', false],
                ['Map IP addresses to MAC addresses', true],
                ['Route packets to the correct subnet', false],
                ['Translate data to a readable format', false],
                ['Encrypt data during transmission', false],
            ],
            [
                ['64', false],
                ['128', true],
                ['32', false],
                ['256', false],
                ['512', false],
            ],
            [
                ['Virtual Logical Area Network', false],
                ['Virtual LAN', false],
                ['Virtual Licensed Area Network', false],
                ['Virtual Local Area Network', true],
                ['Virtual Layer Access Network', false],
            ],
            [
                ['Forward packets based on IP addresses', true],
                ['Regenerate weak signals', false],
                ['Connect computers in a LAN', false],
                ['Translate hostnames to IP addresses', false],
                ['Monitor network traffic', false],
            ],
            [
                ['DNS', false],
                ['SNMP', false],
                ['DHCP', true],
                ['ARP', false],
                ['NAT', false],
            ],
            [
                ['Route packets across networks', false],
                ['Encrypt sensitive data', false],
                ['Monitor network performance', false],
                ['Control inbound and outbound network traffic', true],
                ['Convert private IP addresses to public IP addresses', false],
            ],
            [
                ['TCP is connectionless; UDP is connection-oriented', false],
                ['TCP is faster; UDP is slower', false],
                ['TCP is reliable; UDP is unreliable', true],
                ['TCP operates at Layer 3; UDP operates at Layer 4', false],
                ['None of the above', false],
            ],
            [
                ['traceroute', false],
                ['netstat', false],
                ['route print', true],
                ['ifconfig', false],
                ['ipconfig', false],
            ],
            [
                ['Encrypt communication', false],
                ['Map IP addresses to MAC addresses', false],
                ['Translate private IP addresses to public IP addresses', true],
                ['Assign dynamic IP addresses', false],
                ['Optimize network bandwidth', false],
            ],
            [
                ['FTP', false],
                ['TFTP', false],
                ['SCP', false],
                ['SFTP', true],
                ['HTTP', false],
            ],
            [
                ['192.168.0.0 – 192.168.255.255', true],
                ['10.0.0.0 – 10.255.255.255', false],
                ['172.16.0.0 – 172.31.255.255', false],
                ['224.0.0.0 – 239.255.255.255', false],
                ['127.0.0.0 – 127.255.255.255', false],
            ],
            [
                ['Physical', false],
                ['Data Link', true],
                ['Network', false],
                ['Transport', false],
                ['Application', false],
            ],
            [
                ['DNS translates domain names (e.g., www.example.com) into IP addresses.', true],
                ['DNS is only used for email communication.', false],
                ['DNS is not necessary for browsing the internet.', false],
                ['DNS is only used for local area networks.', false],
                ['DNS is a complex protocol that is difficult to understand.', false],
            ],

            // Advanced Networking Questions
            [
                ['To assign IP addresses dynamically', false],
                ['To identify the host portion of an IP address', false],
                ['To define the network and host portions of an IP address', true],
                ['To secure the network from external threats', false],
                ['To optimize routing decisions', false],
            ],
            [
                ['RIP', false],
                ['OSPF', true],
                ['BGP', false],
                ['EIGRP', false],
                ['IS-IS', false],
            ],
            [
                ['TCP is faster than UDP', false],
                ['UDP is connection-oriented, while TCP is connectionless', false],
                ['TCP ensures reliable data transfer, while UDP does not', true],
                ['UDP uses more bandwidth compared to TCP', false],
                ['TCP is primarily used for streaming, while UDP is not', false],
            ],
            [
                ['By mapping public IP addresses to private IP addresses', true],
                ['By encrypting IP packets for secure transmission', false],
                ['By dividing a single IP address into multiple subnets', false],
                ['By assigning dynamic IP addresses to devices', false],
                ['By filtering and forwarding packets based on port numbers', false],
            ],
            [
                ['Resolves domain names to IP addresses', false],
                ['Maps MAC addresses to IP addresses', true],
                ['Translates IPv6 to IPv4', false],
                [' Maintains routing tables', false],
                ['Encrypts data packets', false],
            ],
            [
                ['It restricts traffic between VLANs', false],
                ['It carries traffic for multiple VLANs', true],
                ['It isolates VLAN traffic to specific devices', false],
                ['It converts broadcast domains into collision domains', false],
                ['It dynamically assigns devices to VLANs', false],
            ],
            [
                ['IP conflicts', false],
                ['Routing loops', false],
                ['Broadcast storms', true],
                ['Packet fragmentation', false],
                ['Unauthorized access', false],
            ],
            [
                ['IPv4 uses 64-bit addressing, while IPv6 uses 128-bit', false],
                ['IPv4 is faster than IPv6', false],
                ['IPv4 supports fewer hosts per network than IPv6', true],
                ['IPv6 does not support NAT, while IPv4 does', false],
                ['IPv4 does not support multicast, while IPv6 does', false],
            ],
            [
                ['It uses static routing to configure networks', false],
                ['It separates the control plane from the data plane', true],
                ['It requires specialized hardware to function', false],
                ['It is only compatible with IPv6 networks', false],
                ['It replaces firewalls in enterprise setups', false],
            ],
            [
                ['By analyzing packet headers and payloads', true],
                ['By encrypting all incoming and outgoing traffic', false],
                ['By ensuring no collisions occur in the network', false],
                ['By assigning IP addresses dynamically', false],
                ['By converting public IPs to private IPs', false],
            ],
            [
                ['Simplifies VLAN configuration', false],
                ['Reduces latency in network traffic', true],
                ['Increases the maximum bandwidth of a link', false],
                ['Facilitates end-to-end encryption', false],
                ['Enables dynamic IP addressing', false],
            ],
            [
                ['Higher transmission speed', false],
                ['Unlimited IP address availability', true],
                ['Better integration with wireless networks', false],
                ['Simplified packet fragmentation', false],
                ['Enhanced multicast capabilities', false],
            ],
            [
                ['ping', false],
                ['traceroute', false],
                ['nslookup', true],
                ['netstat', false],
                ['telnet', false],
            ],
            [
                ['Security protocols', false],
                ['Bandwidth allocation for critical applications', true],
                ['Firewall rule enforcement', false],
                ['Dynamic IP addressing', false],
                ['Packet retransmission in case of loss', false],
            ],
            [
                ['To provide IP routing services', false],
                ['To enable MAC address filtering', false],
                ['To secure access to network devices through authentication', true],
                ['To monitor traffic flow between VLANs', false],
                ['To enforce data encryption between endpoints', false],
            ],
        ];

        $questions = Question::all();

        foreach ($questions as $index => $question) {
            if (isset($options[$index])) {
                foreach ($options[$index] as $option) {
                    Option::create([
                        'question_id' => $question->id,
                        'option_text' => $option[0],
                        'is_correct' => $option[1],
                    ]);
                }
            }
        }
    }
}