<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Category;
use App\Models\Level;
use App\Models\Stage2Question;

class Stage2QuestionsSeeder extends Seeder
{
    public function run(): void
    {
        // Disable foreign key checks to allow truncation
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        // Truncate the stage2_questions table to avoid duplicates
        DB::table('stage2_questions')->truncate();

        // Fetch or create category and level data
        $sqaCategory = Category::firstOrCreate(['name' => 'SQA']);
        $networkingCategory = Category::firstOrCreate(['name' => 'Networking']);
        
        $basicLevel = Level::firstOrCreate(
            ['name' => 'Basic'],
            ['time_limit' => 30]
        );
        $intermediateLevel = Level::firstOrCreate(
            ['name' => 'Intermediate'],
            ['time_limit' => 45]
        );
        $advancedLevel = Level::firstOrCreate(
            ['name' => 'Advanced'],
            ['time_limit' => 60]
        );

        // Stage 2 Questions with dynamic category and level IDs
        $questions = [
            // SQA Basic (10 questions for beginners)
            [
                'question_text' => 'What is the main goal of software testing?',
                'image_path' => 'Q1.png',
                'option_1' => 'To write code',
                'option_2' => 'To design the user interface',
                'option_3' => 'To find defects in the software',
                'option_4' => 'To install the software',
                'option_5' => 'None',
                'correct_option' => 3,
                'category_id' => $sqaCategory->id,
                'level_id' => $basicLevel->id,
            ],
            [
                'question_text' => 'What is a test case?',
                'image_path' => 'Q2.png',
                'option_1' => 'A set of steps to test a feature',
                'option_2' => 'A tool for coding',
                'option_3' => 'A type of software',
                'option_4' => 'A user manual',
                'option_5' => 'None',
                'correct_option' => 1,
                'category_id' => $sqaCategory->id,
                'level_id' => $basicLevel->id,
            ],
            [
                'question_text' => 'What does a bug mean in software testing?',
                'image_path' => 'Q3.png',
                'option_1' => 'A new feature',
                'option_2' => 'An error in the software',
                'option_3' => 'A type of test',
                'option_4' => 'A user requirement',
                'option_5' => 'None',
                'correct_option' => 2,
                'category_id' => $sqaCategory->id,
                'level_id' => $basicLevel->id,
            ],
            [
                'question_text' => 'What is a test plan used for?',
                'image_path' => 'Q4.png',
                'option_1' => 'To write code',
                'option_2' => 'To fix bugs',
                'option_3' => 'To create software',
                'option_4' => 'To describe how testing will be done',
                'option_5' => 'None',
                'correct_option' => 4,
                'category_id' => $sqaCategory->id,
                'level_id' => $basicLevel->id,
            ],
            [
                'question_text' => 'What is a test environment?',
                'image_path' => 'Q5.png',
                'option_1' => 'A place to write code',
                'option_2' => 'A setup where tests are run',
                'option_3' => 'A type of software',
                'option_4' => 'A user guide',
                'option_5' => 'None',
                'correct_option' => 2,
                'category_id' => $sqaCategory->id,
                'level_id' => $basicLevel->id,
            ],
            [
                'question_text' => 'What is the purpose of a defect report?',
                'image_path' => 'Q6.png',
                'option_1' => 'To design new features',
                'option_2' => 'To write test cases',
                'option_3' => 'To document issues found during testing',
                'option_4' => 'To install software',
                'option_5' => 'None',
                'correct_option' => 3,
                'category_id' => $sqaCategory->id,
                'level_id' => $basicLevel->id,
            ],
            [
                'question_text' => 'What is manual testing?',
                'image_path' => 'Q7.png',
                'option_1' => 'Testing done by a computer',
                'option_2' => 'Testing hardware',
                'option_3' => 'Testing network speed',
                'option_4' => 'Testing done by a person',
                'option_5' => 'None',
                'correct_option' => 4,
                'category_id' => $sqaCategory->id,
                'level_id' => $basicLevel->id,
            ],
            [
                'question_text' => 'What is a test result?',
                'image_path' => 'Q8.png',
                'option_1' => 'The outcome of running a test case',
                'option_2' => 'A new software feature',
                'option_3' => 'A type of bug',
                'option_4' => 'A user requirement',
                'option_5' => 'None',
                'correct_option' => 1,
                'category_id' => $sqaCategory->id,
                'level_id' => $basicLevel->id,
            ],
            [
                'question_text' => 'What is the role of a tester?',
                'image_path' => 'Q9.png',
                'option_1' => 'To write code',
                'option_2' => 'To design the software',
                'option_3' => 'To manage the project',
                'option_4' => 'To find and report defects',
                'option_5' => 'None',
                'correct_option' => 4,
                'category_id' => $sqaCategory->id,
                'level_id' => $basicLevel->id,
            ],
            [
                'question_text' => 'What is a test script?',
                'image_path' => 'Q10.png',
                'option_1' => 'A programming language',
                'option_2' => 'Instructions to perform a test',
                'option_3' => 'A type of software',
                'option_4' => 'A defect report',
                'option_5' => 'None',
                'correct_option' => 2,
                'category_id' => $sqaCategory->id,
                'level_id' => $basicLevel->id,
            ],
            // SQA Intermediate (10 questions for moderately experienced employees)
            [
                'question_text' => 'What is the purpose of regression testing?',
                'image_path' => 'Q11.png',
                'option_1' => 'To test new features',
                'option_2' => 'To test hardware',
                'option_3' => 'To ensure existing features still work',
                'option_4' => 'To design test cases',
                'option_5' => 'None',
                'correct_option' => 3,
                'category_id' => $sqaCategory->id,
                'level_id' => $intermediateLevel->id,
            ],
            [
                'question_text' => 'What is integration testing?',
                'image_path' => 'Q12.png',
                'option_1' => 'Testing individual components',
                'option_2' => 'Testing how components work together',
                'option_3' => 'Testing the user interface',
                'option_4' => 'Testing network performance',
                'option_5' => 'None',
                'correct_option' => 2,
                'category_id' => $sqaCategory->id,
                'level_id' => $intermediateLevel->id,
            ],
            [
                'question_text' => 'What is black-box testing?',
                'image_path' => 'Q13.png',
                'option_1' => 'Testing with knowledge of the code',
                'option_2' => 'Testing only performance',
                'option_3' => 'Testing only security',
                'option_4' => 'Testing without knowledge of the code',
                'option_5' => 'None',
                'correct_option' => 4,
                'category_id' => $sqaCategory->id,
                'level_id' => $intermediateLevel->id,
            ],
            [
                'question_text' => 'What is the purpose of load testing?',
                'image_path' => 'Q14.png',
                'option_1' => 'To test system behavior under heavy load',
                'option_2' => 'To test usability',
                'option_3' => 'To test security',
                'option_4' => 'To test code coverage',
                'option_5' => 'None',
                'correct_option' => 1,
                'category_id' => $sqaCategory->id,
                'level_id' => $intermediateLevel->id,
            ],
            [
                'question_text' => 'What is a test suite?',
                'image_path' => 'Q15.png',
                'option_1' => 'A single test case',
                'option_2' => 'A group of related test cases',
                'option_3' => 'A defect tracking tool',
                'option_4' => 'A performance report',
                'option_5' => 'None',
                'correct_option' => 2,
                'category_id' => $sqaCategory->id,
                'level_id' => $intermediateLevel->id,
            ],
            [
                'question_text' => 'What is API testing?',
                'image_path' => 'Q16.png',
                'option_1' => 'Testing the user interface',
                'option_2' => 'Testing hardware components',
                'option_3' => 'Testing application programming interfaces',
                'option_4' => 'Testing network speed',
                'option_5' => 'None',
                'correct_option' => 3,
                'category_id' => $sqaCategory->id,
                'level_id' => $intermediateLevel->id,
            ],
            [
                'question_text' => 'What is the benefit of test automation?',
                'image_path' => 'Q17.png',
                'option_1' => 'Increases manual effort',
                'option_2' => 'Reduces test execution time',
                'option_3' => 'Reduces test coverage',
                'option_4' => 'Increases defect rate',
                'option_5' => 'None',
                'correct_option' => 2,
                'category_id' => $sqaCategory->id,
                'level_id' => $intermediateLevel->id,
            ],
            [
                'question_text' => 'What is stress testing?',
                'image_path' => 'Q18.png',
                'option_1' => 'Testing under normal conditions',
                'option_2' => 'Testing user interfaces',
                'option_3' => 'Testing beyond normal capacity',
                'option_4' => 'Testing security protocols',
                'option_5' => 'None',
                'correct_option' => 3,
                'category_id' => $sqaCategory->id,
                'level_id' => $intermediateLevel->id,
            ],
            [
                'question_text' => 'What does test coverage measure?',
                'image_path' => 'Q19.png',
                'option_1' => 'Number of defects found',
                'option_2' => 'Time taken to execute tests',
                'option_3' => 'Number of test cases written',
                'option_4' => 'Percentage of code or requirements tested',
                'option_5' => 'None',
                'correct_option' => 4,
                'category_id' => $sqaCategory->id,
                'level_id' => $intermediateLevel->id,
            ],
            [
                'question_text' => 'What is a test harness?',
                'image_path' => 'Q20.png',
                'option_1' => 'A set of tools to test software',
                'option_2' => 'A defect tracking tool',
                'option_3' => 'A test plan document',
                'option_4' => 'A user manual',
                'option_5' => 'None',
                'correct_option' => 1,
                'category_id' => $sqaCategory->id,
                'level_id' => $intermediateLevel->id,
            ],
            // SQA Advanced (10 questions for experienced employees)
            [
                'question_text' => 'What is mutation testing used for?',
                'image_path' => 'Q21.png',
                'option_1' => 'To evaluate test case effectiveness by altering code',
                'option_2' => 'To test performance under load',
                'option_3' => 'To test user interfaces',
                'option_4' => 'To test network protocols',
                'option_5' => 'None',
                'correct_option' => 1,
                'category_id' => $sqaCategory->id,
                'level_id' => $advancedLevel->id,
            ],
            [
                'question_text' => 'What is pairwise testing designed to do?',
                'image_path' => 'Q22.png',
                'option_1' => 'Test all possible input combinations',
                'option_2' => 'Test pairs of input combinations efficiently',
                'option_3' => 'Test random inputs only',
                'option_4' => 'Test performance metrics',
                'option_5' => 'None',
                'correct_option' => 2,
                'category_id' => $sqaCategory->id,
                'level_id' => $advancedLevel->id,
            ],
            [
                'question_text' => 'What is the goal of shift-left testing?',
                'image_path' => 'Q23.png',
                'option_1' => 'To delay testing until deployment',
                'option_2' => 'To test only security features',
                'option_3' => 'To start testing early in development',
                'option_4' => 'To automate all tests',
                'option_5' => 'None',
                'correct_option' => 3,
                'category_id' => $sqaCategory->id,
                'level_id' => $advancedLevel->id,
            ],
            [
                'question_text' => 'What is chaos engineering in testing?',
                'image_path' => 'Q24.png',
                'option_1' => 'Testing user interfaces',
                'option_2' => 'Testing performance under normal conditions',
                'option_3' => 'Testing code coverage',
                'option_4' => 'Introducing controlled failures to test system resilience',
                'option_5' => 'None',
                'correct_option' => 4,
                'category_id' => $sqaCategory->id,
                'level_id' => $advancedLevel->id,
            ],
            [
                'question_text' => 'What is exploratory testing?',
                'image_path' => 'Q25.png',
                'option_1' => 'Testing with predefined test cases',
                'option_2' => 'Dynamic testing without predefined scripts',
                'option_3' => 'Automated performance testing',
                'option_4' => 'Testing only security vulnerabilities',
                'option_5' => 'None',
                'correct_option' => 2,
                'category_id' => $sqaCategory->id,
                'level_id' => $advancedLevel->id,
            ],
            [
                'question_text' => 'What is fuzz testing used for?',
                'image_path' => 'Q26.png',
                'option_1' => 'Testing with valid inputs only',
                'option_2' => 'Testing user interfaces',
                'option_3' => 'Testing network performance',
                'option_4' => 'Testing with random or invalid inputs',
                'option_5' => 'None',
                'correct_option' => 4,
                'category_id' => $sqaCategory->id,
                'level_id' => $advancedLevel->id,
            ],
            [
                'question_text' => 'What is the purpose of model-based testing?',
                'image_path' => 'Q27.png',
                'option_1' => 'Testing based on random inputs',
                'option_2' => 'Testing only performance',
                'option_3' => 'Testing using system behavior models',
                'option_4' => 'Testing only user interfaces',
                'option_5' => 'None',
                'correct_option' => 3,
                'category_id' => $sqaCategory->id,
                'level_id' => $advancedLevel->id,
            ],
            [
                'question_text' => 'What is static testing?',
                'image_path' => 'Q28.png',
                'option_1' => 'Testing by executing the software',
                'option_2' => 'Testing without executing the software',
                'option_3' => 'Testing only security features',
                'option_4' => 'Testing only performance',
                'option_5' => 'None',
                'correct_option' => 2,
                'category_id' => $sqaCategory->id,
                'level_id' => $advancedLevel->id,
            ],
            [
                'question_text' => 'What is the goal of usability testing?',
                'image_path' => 'Q29.png',
                'option_1' => 'To evaluate user experience and interface',
                'option_2' => 'To test system performance',
                'option_3' => 'To test code coverage',
                'option_4' => 'To test network protocols',
                'option_5' => 'None',
                'correct_option' => 1,
                'category_id' => $sqaCategory->id,
                'level_id' => $advancedLevel->id,
            ],
            [
                'question_text' => 'What is risk-based testing?',
                'image_path' => 'Q30.png',
                'option_1' => 'Testing all areas equally',
                'option_2' => 'Testing only performance',
                'option_3' => 'Testing only user interfaces',
                'option_4' => 'Prioritizing testing based on risk',
                'option_5' => 'None',
                'correct_option' => 4,
                'category_id' => $sqaCategory->id,
                'level_id' => $advancedLevel->id,
            ],
            // Networking Basic (10 questions for beginners)
            [
                'question_text' => 'What is a network?',
                'image_path' => 'Q31.png',
                'option_1' => 'A type of software',
                'option_2' => 'A single computer',
                'option_3' => 'A group of connected computers',
                'option_4' => 'A programming language',
                'option_5' => 'None',
                'correct_option' => 3,
                'category_id' => $networkingCategory->id,
                'level_id' => $basicLevel->id,
            ],
            [
                'question_text' => 'What does a router do?',
                'image_path' => 'Q32.png',
                'option_1' => 'Connects different networks',
                'option_2' => 'Stores data',
                'option_3' => 'Writes code',
                'option_4' => 'Tests software',
                'option_5' => 'None',
                'correct_option' => 1,
                'category_id' => $networkingCategory->id,
                'level_id' => $basicLevel->id,
            ],
            [
                'question_text' => 'What is an IP address?',
                'image_path' => 'Q33.png',
                'option_1' => 'A type of cable',
                'option_2' => 'A unique address for a device on a network',
                'option_3' => 'A software program',
                'option_4' => 'A firewall setting',
                'option_5' => 'None',
                'correct_option' => 2,
                'category_id' => $networkingCategory->id,
                'level_id' => $basicLevel->id,
            ],
            [
                'question_text' => 'What is the purpose of a firewall?',
                'image_path' => 'Q34.png',
                'option_1' => 'To write code',
                'option_2' => 'To store data',
                'option_3' => 'To design software',
                'option_4' => 'To protect a network from unauthorized access',
                'option_5' => 'None',
                'correct_option' => 4,
                'category_id' => $networkingCategory->id,
                'level_id' => $basicLevel->id,
            ],
            [
                'question_text' => 'What does DNS stand for?',
                'image_path' => 'Q35.png',
                'option_1' => 'Domain Name System',
                'option_2' => 'Dynamic Network Service',
                'option_3' => 'Data Network System',
                'option_4' => 'Domain Network Security',
                'option_5' => 'None',
                'correct_option' => 1,
                'category_id' => $networkingCategory->id,
                'level_id' => $basicLevel->id,
            ],
            [
                'question_text' => 'What is a switch used for in a network?',
                'image_path' => 'Q36.png',
                'option_1' => 'To connect to the internet',
                'option_2' => 'To connect devices within the same network',
                'option_3' => 'To write code',
                'option_4' => 'To test software',
                'option_5' => 'None',
                'correct_option' => 2,
                'category_id' => $networkingCategory->id,
                'level_id' => $basicLevel->id,
            ],
            [
                'question_text' => 'What is bandwidth?',
                'image_path' => 'Q37.png',
                'option_1' => 'A type of firewall',
                'option_2' => 'A programming language',
                'option_3' => 'The amount of data that can be sent over a network',
                'option_4' => 'A type of router',
                'option_5' => 'None',
                'correct_option' => 3,
                'category_id' => $networkingCategory->id,
                'level_id' => $basicLevel->id,
            ],
            [
                'question_text' => 'What does a modem do?',
                'image_path' => 'Q38.png',
                'option_1' => 'Tests software',
                'option_2' => 'Stores data',
                'option_3' => 'Writes code',
                'option_4' => 'Connects a network to the internet',
                'option_5' => 'None',
                'correct_option' => 4,
                'category_id' => $networkingCategory->id,
                'level_id' => $basicLevel->id,
            ],
            [
                'question_text' => 'What is a LAN?',
                'image_path' => 'Q39.png',
                'option_1' => 'A local area network',
                'option_2' => 'A programming language',
                'option_3' => 'A type of software',
                'option_4' => 'A firewall setting',
                'option_5' => 'None',
                'correct_option' => 1,
                'category_id' => $networkingCategory->id,
                'level_id' => $basicLevel->id,
            ],
            [
                'question_text' => 'What is the role of a network cable?',
                'image_path' => 'Q40.png',
                'option_1' => 'To write code',
                'option_2' => 'To test software',
                'option_3' => 'To connect devices physically in a network',
                'option_4' => 'To store data',
                'option_5' => 'None',
                'correct_option' => 3,
                'category_id' => $networkingCategory->id,
                'level_id' => $basicLevel->id,
            ],
            // Networking Intermediate (10 questions for moderately experienced employees)
            [
                'question_text' => 'What does NAT stand for?',
                'image_path' => 'Q41.png',
                'option_1' => 'Network Address Translation',
                'option_2' => 'Network Access Transmission',
                'option_3' => 'Network Address Transmission',
                'option_4' => 'Network Access Translation',
                'option_5' => 'None',
                'correct_option' => 1,
                'category_id' => $networkingCategory->id,
                'level_id' => $intermediateLevel->id,
            ],
            [
                'question_text' => 'What is the main function of TCP?',
                'image_path' => 'Q42.png',
                'option_1' => 'To transmit data without error checking',
                'option_2' => 'To manage network routing',
                'option_3' => 'To provide reliable, connection-oriented communication',
                'option_4' => 'To handle email transmission',
                'option_5' => 'None',
                'correct_option' => 3,
                'category_id' => $networkingCategory->id,
                'level_id' => $intermediateLevel->id,
            ],
            [
                'question_text' => 'What is a VLAN used for?',
                'image_path' => 'Q43.png',
                'option_1' => 'To encrypt network traffic',
                'option_2' => 'To segment a network logically',
                'option_3' => 'To assign IP addresses',
                'option_4' => 'To connect to the internet',
                'option_5' => 'None',
                'correct_option' => 2,
                'category_id' => $networkingCategory->id,
                'level_id' => $intermediateLevel->id,
            ],
            [
                'question_text' => 'What is the purpose of ARP?',
                'image_path' => 'Q44.png',
                'option_1' => 'To encrypt data',
                'option_2' => 'To assign IP addresses',
                'option_3' => 'To manage routing tables',
                'option_4' => 'To map IP addresses to MAC addresses',
                'option_5' => 'None',
                'correct_option' => 4,
                'category_id' => $networkingCategory->id,
                'level_id' => $intermediateLevel->id,
            ],
            [
                'question_text' => 'What is a VPN used for?',
                'image_path' => 'Q45.png',
                'option_1' => 'To increase network speed',
                'option_2' => 'To create a secure connection over the internet',
                'option_3' => 'To assign IP addresses',
                'option_4' => 'To manage routing',
                'option_5' => 'None',
                'correct_option' => 2,
                'category_id' => $networkingCategory->id,
                'level_id' => $intermediateLevel->id,
            ],
            [
                'question_text' => 'What does UDP stand for?',
                'image_path' => 'Q46.png',
                'option_1' => 'User Datagram Protocol',
                'option_2' => 'Unified Data Protocol',
                'option_3' => 'User Data Protocol',
                'option_4' => 'Unified Datagram Protocol',
                'option_5' => 'None',
                'correct_option' => 1,
                'category_id' => $networkingCategory->id,
                'level_id' => $intermediateLevel->id,
            ],
            [
                'question_text' => 'What is the purpose of QoS?',
                'image_path' => 'Q47.png',
                'option_1' => 'To assign IP addresses',
                'option_2' => 'To encrypt data',
                'option_3' => 'To prioritize network traffic',
                'option_4' => 'To connect networks',
                'option_5' => 'None',
                'correct_option' => 3,
                'category_id' => $networkingCategory->id,
                'level_id' => $intermediateLevel->id,
            ],
            [
                'question_text' => 'What is a subnet mask used for?',
                'image_path' => 'Q48.png',
                'option_1' => 'To encrypt data',
                'option_2' => 'To separate network and host portions of an IP address',
                'option_3' => 'To assign IP addresses',
                'option_4' => 'To manage routing',
                'option_5' => 'None',
                'correct_option' => 2,
                'category_id' => $networkingCategory->id,
                'level_id' => $intermediateLevel->id,
            ],
            [
                'question_text' => 'What is a MAC address?',
                'image_path' => 'Q49.png',
                'option_1' => 'A type of protocol',
                'option_2' => 'A firewall setting',
                'option_3' => 'A routing table',
                'option_4' => 'A unique identifier for a network device',
                'option_5' => 'None',
                'correct_option' => 4,
                'category_id' => $networkingCategory->id,
                'level_id' => $intermediateLevel->id,
            ],
            [
                'question_text' => 'What is the maximum length of a CAT5 Ethernet cable?',
                'image_path' => 'Q50.png',
                'option_1' => '100 meters',
                'option_2' => '50 meters',
                'option_3' => '150 meters',
                'option_4' => '200 meters',
                'option_5' => 'None',
                'correct_option' => 1,
                'category_id' => $networkingCategory->id,
                'level_id' => $intermediateLevel->id,
            ],
            // Networking Advanced (10 questions for experienced employees)
            [
                'question_text' => 'What is BGP used for in large networks?',
                'image_path' => 'Q51.png',
                'option_1' => 'To assign IP addresses',
                'option_2' => 'To exchange routing information between autonomous systems',
                'option_3' => 'To encrypt network traffic',
                'option_4' => 'To manage VLANs',
                'option_5' => 'None',
                'correct_option' => 2,
                'category_id' => $networkingCategory->id,
                'level_id' => $advancedLevel->id,
            ],
            [
                'question_text' => 'What does SDN stand for and its purpose?',
                'image_path' => 'Q52.png',
                'option_1' => 'Software Defined Networking, for programmable network control',
                'option_2' => 'Secure Data Networking, for encryption',
                'option_3' => 'Static Data Networking, for fixed routing',
                'option_4' => 'Software Designed Networking, for hardware design',
                'option_5' => 'None',
                'correct_option' => 1,
                'category_id' => $networkingCategory->id,
                'level_id' => $advancedLevel->id,
            ],
            [
                'question_text' => 'What is the primary function of MPLS?',
                'image_path' => 'Q53.png',
                'option_1' => 'To assign IP addresses',
                'option_2' => 'To encrypt network traffic',
                'option_3' => 'To direct data using labels for efficient routing',
                'option_4' => 'To manage QoS settings',
                'option_5' => 'None',
                'correct_option' => 3,
                'category_id' => $networkingCategory->id,
                'level_id' => $advancedLevel->id,
            ],
            [
                'question_text' => 'What is the purpose of the Spanning Tree Protocol (STP)?',
                'image_path' => 'Q54.png',
                'option_1' => 'To assign IP addresses',
                'option_2' => 'To encrypt data',
                'option_3' => 'To manage VLANs',
                'option_4' => 'To prevent loops in network topology',
                'option_5' => 'None',
                'correct_option' => 4,
                'category_id' => $networkingCategory->id,
                'level_id' => $advancedLevel->id,
            ],
            [
                'question_text' => 'What does Network Function Virtualization (NFV) replace?',
                'image_path' => 'Q55.png',
                'option_1' => 'Physical network hardware with virtualized functions',
                'option_2' => 'Network cables',
                'option_3' => 'Firewalls only',
                'option_4' => 'Routing protocols',
                'option_5' => 'None',
                'correct_option' => 1,
                'category_id' => $networkingCategory->id,
                'level_id' => $advancedLevel->id,
            ],
            [
                'question_text' => 'What is the purpose of OSPF?',
                'image_path' => 'Q56.png',
                'option_1' => 'To encrypt network traffic',
                'option_2' => 'To manage dynamic routing within an autonomous system',
                'option_3' => 'To assign IP addresses',
                'option_4' => 'To provide DNS services',
                'option_5' => 'None',
                'correct_option' => 2,
                'category_id' => $networkingCategory->id,
                'level_id' => $advancedLevel->id,
            ],
            [
                'question_text' => 'What is a DMZ in networking?',
                'image_path' => 'Q57.png',
                'option_1' => 'A routing protocol',
                'option_2' => 'A type of encryption',
                'option_3' => 'A subnetwork for public-facing services',
                'option_4' => 'A network cable standard',
                'option_5' => 'None',
                'correct_option' => 3,
                'category_id' => $networkingCategory->id,
                'level_id' => $advancedLevel->id,
            ],
            [
                'question_text' => 'What is the purpose of load balancing?',
                'image_path' => 'Q58.png',
                'option_1' => 'To encrypt network traffic',
                'option_2' => 'To assign IP addresses',
                'option_3' => 'To secure firewalls',
                'option_4' => 'To distribute traffic across multiple servers',
                'option_5' => 'None',
                'correct_option' => 4,
                'category_id' => $networkingCategory->id,
                'level_id' => $advancedLevel->id,
            ],
            [
                'question_text' => 'What does IGMP stand for?',
                'image_path' => 'Q59.png',
                'option_1' => 'Internet Group Management Protocol',
                'option_2' => 'Internal Gateway Management Protocol',
                'option_3' => 'Internet Gateway Messaging Protocol',
                'option_4' => 'Internal Group Messaging Protocol',
                'option_5' => 'None',
                'correct_option' => 1,
                'category_id' => $networkingCategory->id,
                'level_id' => $advancedLevel->id,
            ],
            [
                'question_text' => 'What is the role of a proxy server?',
                'image_path' => 'Q60.png',
                'option_1' => 'To assign IP addresses',
                'option_2' => 'To act as an intermediary between clients and servers',
                'option_3' => 'To route network traffic',
                'option_4' => 'To store network data',
                'option_5' => 'None',
                'correct_option' => 2,
                'category_id' => $networkingCategory->id,
                'level_id' => $advancedLevel->id,
            ],
        ];

        DB::table('stage2_questions')->insert($questions);

        // Re-enable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}